from scrapy.spider import BaseSpider
from scrapy.selector import HtmlXPathSelector
import re

from qb_scraper.items import CfbQbItem

class QbSpider(BaseSpider):
    name = "qb_stats"
    allowed_domains = ["sports-reference.com"]
    start_urls = [
        "http://www.sports-reference.com/cfb/players/troy-aikman-1.html",
        "http://www.sports-reference.com/cfb/players/frankie-albert-1.html",
        "http://www.sports-reference.com/cfb/players/derek-anderson-1.html",
        "http://www.sports-reference.com/cfb/players/david-archer-1.html",
        "http://www.sports-reference.com/cfb/players/bob-avellini-1.html",
        "http://www.sports-reference.com/cfb/players/tony-banks-1.html",
        "http://www.sports-reference.com/cfb/players/steve-bartkowski-1.html",
        "http://www.sports-reference.com/cfb/players/charlie-batch-1.html",
        "http://www.sports-reference.com/cfb/players/sammy-baugh-1.html",
        "http://www.sports-reference.com/cfb/players/pete-beathard-1.html",
        "http://www.sports-reference.com/cfb/players/bob-berry-1.html",
        "http://www.sports-reference.com/cfb/players/bob-berry-2.html",
        "http://www.sports-reference.com/cfb/players/steve-beuerlein-1.html",
        "http://www.sports-reference.com/cfb/players/todd-blackledge-1.html",
        "http://www.sports-reference.com/cfb/players/jeff-blake-1.html",
        "http://www.sports-reference.com/cfb/players/jeff-blake-2.html",
        "http://www.sports-reference.com/cfb/players/drew-bledsoe-1.html",
        "http://www.sports-reference.com/cfb/players/kyle-boller-1.html",
        "http://www.sports-reference.com/cfb/players/brooks-bollinger-1.html",
        "http://www.sports-reference.com/cfb/players/steve-bono-1.html",
        "http://www.sports-reference.com/cfb/players/mike-boryla-1.html",
        "http://www.sports-reference.com/cfb/players/sam-bradford-1.html",
        "http://www.sports-reference.com/cfb/players/tom-brady-1.html",
        "http://www.sports-reference.com/cfb/players/tom-brady-2.html",
        "http://www.sports-reference.com/cfb/players/drew-brees-1.html",
        "http://www.sports-reference.com/cfb/players/bubby-brister-1.html",
        "http://www.sports-reference.com/cfb/players/john-brodie-1.html",
        "http://www.sports-reference.com/cfb/players/aaron-brooks-1.html",
        "http://www.sports-reference.com/cfb/players/mark-brunell-1.html",
        "http://www.sports-reference.com/cfb/players/marc-bulger-1.html",
        "http://www.sports-reference.com/cfb/players/jason-campbell-1.html",
        "http://www.sports-reference.com/cfb/players/scott-campbell-1.html",
        "http://www.sports-reference.com/cfb/players/scott-campbell-2.html",
        "http://www.sports-reference.com/cfb/players/david-carr-1.html",
        "http://www.sports-reference.com/cfb/players/david-carr-2.html",
        "http://www.sports-reference.com/cfb/players/quincy-carter-1.html",
        "http://www.sports-reference.com/cfb/players/virgil-carter-1.html",
        "http://www.sports-reference.com/cfb/players/matt-cassel-1.html",
        "http://www.sports-reference.com/cfb/players/matt-cavanaugh-1.html",
        "http://www.sports-reference.com/cfb/players/chris-chandler-1.html",
        "http://www.sports-reference.com/cfb/players/paul-christman-1.html",
        "http://www.sports-reference.com/cfb/players/jimmy-clausen-1.html",
        "http://www.sports-reference.com/cfb/players/kellen-clemens-1.html",
        "http://www.sports-reference.com/cfb/players/kerry-collins-1.html",
        "http://www.sports-reference.com/cfb/players/todd-collins-1.html",
        "http://www.sports-reference.com/cfb/players/charlie-conerly-1.html",
        "http://www.sports-reference.com/cfb/players/greg-cook-1.html",
        "http://www.sports-reference.com/cfb/players/tim-couch-1.html",
        "http://www.sports-reference.com/cfb/players/daunte-culpepper-1.html",
        "http://www.sports-reference.com/cfb/players/randall-cunningham-1.html",
        "http://www.sports-reference.com/cfb/players/gary-cuozzo-1.html",
        "http://www.sports-reference.com/cfb/players/jay-cutler-1.html",
        "http://www.sports-reference.com/cfb/players/andy-dalton-1.html",
        "http://www.sports-reference.com/cfb/players/gary-danielson-1.html",
        "http://www.sports-reference.com/cfb/players/bob-davis-1.html",
        "http://www.sports-reference.com/cfb/players/bob-davis-2.html",
        "http://www.sports-reference.com/cfb/players/bob-davis-3.html",
        "http://www.sports-reference.com/cfb/players/bob-davis-4.html",
        "http://www.sports-reference.com/cfb/players/len-dawson-1.html",
        "http://www.sports-reference.com/cfb/players/jake-delhomme-1.html",
        "http://www.sports-reference.com/cfb/players/ty-detmer-1.html",
        "http://www.sports-reference.com/cfb/players/lynn-dickey-1.html",
        "http://www.sports-reference.com/cfb/players/trent-dilfer-1.html",
        "http://www.sports-reference.com/cfb/players/steve-dils-1.html",
        "http://www.sports-reference.com/cfb/players/anthony-dilweg-1.html",
        "http://www.sports-reference.com/cfb/players/ken-dorsey-1.html",
        "http://www.sports-reference.com/cfb/players/ken-dorsey-2.html",
        "http://www.sports-reference.com/cfb/players/bobby-douglass-1.html",
        "http://www.sports-reference.com/cfb/players/tony-eason-1.html",
        "http://www.sports-reference.com/cfb/players/tony-eason-2.html",
        "http://www.sports-reference.com/cfb/players/trent-edwards-1.html",
        "http://www.sports-reference.com/cfb/players/john-elway-1.html",
        "http://www.sports-reference.com/cfb/players/craig-erickson-1.html",
        "http://www.sports-reference.com/cfb/players/boomer-esiason-1.html",
        "http://www.sports-reference.com/cfb/players/vince-evans-1.html",
        "http://www.sports-reference.com/cfb/players/vince-evans-2.html",
        "http://www.sports-reference.com/cfb/players/jim-everett-1.html",
        "http://www.sports-reference.com/cfb/players/jim-everett-2.html",
        "http://www.sports-reference.com/cfb/players/brett-favre-1.html",
        "http://www.sports-reference.com/cfb/players/aj-feeley-1.html",
        "http://www.sports-reference.com/cfb/players/joe-ferguson-1.html",
        "http://www.sports-reference.com/cfb/players/vince-ferragamo-1.html",
        "http://www.sports-reference.com/cfb/players/joe-flacco-1.html",
        "http://www.sports-reference.com/cfb/players/doug-flutie-1.html",
        "http://www.sports-reference.com/cfb/players/dan-fouts-1.html",
        "http://www.sports-reference.com/cfb/players/josh-freeman-1.html",
        "http://www.sports-reference.com/cfb/players/jesse-freitas-1.html",
        "http://www.sports-reference.com/cfb/players/gus-frerotte-1.html",
        "http://www.sports-reference.com/cfb/players/charlie-frye-1.html",
        "http://www.sports-reference.com/cfb/players/steve-fuller-1.html",
        "http://www.sports-reference.com/cfb/players/pat-haden-1.html",
        "http://www.sports-reference.com/cfb/players/john-hadl-1.html",
        "http://www.sports-reference.com/cfb/players/jim-harbaugh-1.html",
        "http://www.sports-reference.com/cfb/players/joey-harrington-1.html",
        "http://www.sports-reference.com/cfb/players/james-harris-1.html",
        "http://www.sports-reference.com/cfb/players/james-harris-2.html",
        "http://www.sports-reference.com/cfb/players/james-harris-3.html",
        "http://www.sports-reference.com/cfb/players/james-harris-4.html",
        "http://www.sports-reference.com/cfb/players/jim-hart-1.html",
        "http://www.sports-reference.com/cfb/players/matt-hasselbeck-1.html",
        "http://www.sports-reference.com/cfb/players/bobby-hebert-1.html",
        "http://www.sports-reference.com/cfb/players/don-heinrich-1.html",
        "http://www.sports-reference.com/cfb/players/chad-henne-1.html",
        "http://www.sports-reference.com/cfb/players/rusty-hilger-1.html",
        "http://www.sports-reference.com/cfb/players/king-hill-1.html",
        "http://www.sports-reference.com/cfb/players/shaun-hill-1.html",
        "http://www.sports-reference.com/cfb/players/eric-hipple-1.html",
        "http://www.sports-reference.com/cfb/players/billy-joe-hobert-1.html",
        "http://www.sports-reference.com/cfb/players/gary-hogeboom-1.html",
        "http://www.sports-reference.com/cfb/players/don-horn-1.html",
        "http://www.sports-reference.com/cfb/players/don-horn-2.html",
        "http://www.sports-reference.com/cfb/players/jeff-hostetler-1.html",
        "http://www.sports-reference.com/cfb/players/bobby-hoying-1.html",
        "http://www.sports-reference.com/cfb/players/damon-huard-1.html",
        "http://www.sports-reference.com/cfb/players/gary-huff-1.html",
        "http://www.sports-reference.com/cfb/players/scott-hunter-1.html",
        "http://www.sports-reference.com/cfb/players/chad-hutchinson-1.html",
        "http://www.sports-reference.com/cfb/players/tarvaris-jackson-1.html",
        "http://www.sports-reference.com/cfb/players/brad-johnson-1.html",
        "http://www.sports-reference.com/cfb/players/brad-johnson-2.html",
        "http://www.sports-reference.com/cfb/players/charley-johnson-1.html",
        "http://www.sports-reference.com/cfb/players/doug-johnson-1.html",
        "http://www.sports-reference.com/cfb/players/doug-johnson-2.html",
        "http://www.sports-reference.com/cfb/players/doug-johnson-3.html",
        "http://www.sports-reference.com/cfb/players/randy-johnson-1.html",
        "http://www.sports-reference.com/cfb/players/randy-johnson-2.html",
        "http://www.sports-reference.com/cfb/players/rob-johnson-1.html",
        "http://www.sports-reference.com/cfb/players/rob-johnson-2.html",
        "http://www.sports-reference.com/cfb/players/rob-johnson-3.html",
        "http://www.sports-reference.com/cfb/players/bert-jones-1.html",
        "http://www.sports-reference.com/cfb/players/sonny-jurgensen-1.html",
        "http://www.sports-reference.com/cfb/players/colin-kaepernick-1.html",
        "http://www.sports-reference.com/cfb/players/danny-kanell-1.html",
        "http://www.sports-reference.com/cfb/players/joe-kapp-1.html",
        "http://www.sports-reference.com/cfb/players/jim-kelly-1.html",
        "http://www.sports-reference.com/cfb/players/jim-kelly-2.html",
        "http://www.sports-reference.com/cfb/players/jeff-kemp-1.html",
        "http://www.sports-reference.com/cfb/players/billy-kilmer-1.html",
        "http://www.sports-reference.com/cfb/players/shaun-king-1.html",
        "http://www.sports-reference.com/cfb/players/david-klingler-1.html",
        "http://www.sports-reference.com/cfb/players/kevin-kolb-1.html",
        "http://www.sports-reference.com/cfb/players/bernie-kosar-1.html",
        "http://www.sports-reference.com/cfb/players/erik-kramer-1.html",
        "http://www.sports-reference.com/cfb/players/tommy-kramer-1.html",
        "http://www.sports-reference.com/cfb/players/daryle-lamonica-1.html",
        "http://www.sports-reference.com/cfb/players/bobby-layne-1.html",
        "http://www.sports-reference.com/cfb/players/ryan-leaf-1.html",
        "http://www.sports-reference.com/cfb/players/byron-leftwich-1.html",
        "http://www.sports-reference.com/cfb/players/matt-leinart-1.html",
        "http://www.sports-reference.com/cfb/players/cleo-lemon-1.html",
        "http://www.sports-reference.com/cfb/players/pete-liske-1.html",
        "http://www.sports-reference.com/cfb/players/mike-livingston-1.html",
        "http://www.sports-reference.com/cfb/players/jake-locker-1.html",
        "http://www.sports-reference.com/cfb/players/neil-lomax-1.html",
        "http://www.sports-reference.com/cfb/players/chuck-long-1.html",
        "http://www.sports-reference.com/cfb/players/jp-losman-1.html",
        "http://www.sports-reference.com/cfb/players/ray-lucas-1.html",
        "http://www.sports-reference.com/cfb/players/andrew-luck-1.html",
        "http://www.sports-reference.com/cfb/players/sid-luckman-1.html",
        "http://www.sports-reference.com/cfb/players/tommy-maddox-1.html",
        "http://www.sports-reference.com/cfb/players/don-majkowski-1.html",
        "http://www.sports-reference.com/cfb/players/mark-malone-1.html",
        "http://www.sports-reference.com/cfb/players/archie-manning-1.html",
        "http://www.sports-reference.com/cfb/players/eli-manning-1.html",
        "http://www.sports-reference.com/cfb/players/peyton-manning-1.html",
        "http://www.sports-reference.com/cfb/players/ted-marchibroda-1.html",
        "http://www.sports-reference.com/cfb/players/dan-marino-1.html",
        "http://www.sports-reference.com/cfb/players/todd-marinovich-1.html",
        "http://www.sports-reference.com/cfb/players/bruce-mathison-1.html",
        "http://www.sports-reference.com/cfb/players/shane-matthews-1.html",
        "http://www.sports-reference.com/cfb/players/josh-mccown-1.html",
        "http://www.sports-reference.com/cfb/players/colt-mccoy-1.html",
        "http://www.sports-reference.com/cfb/players/paul-mcdonald-1.html",
        "http://www.sports-reference.com/cfb/players/jim-mcmahon-1.html",
        "http://www.sports-reference.com/cfb/players/mike-mcmahon-1.html",
        "http://www.sports-reference.com/cfb/players/donovan-mcnabb-1.html",
        "http://www.sports-reference.com/cfb/players/cade-mcnown-1.html",
        "http://www.sports-reference.com/cfb/players/don-meredith-1.html",
        "http://www.sports-reference.com/cfb/players/hugh-millen-1.html",
        "http://www.sports-reference.com/cfb/players/chris-miller-6.html",
        "http://www.sports-reference.com/cfb/players/chris-miller-7.html",
        "http://www.sports-reference.com/cfb/players/chris-miller-8.html",
        "http://www.sports-reference.com/cfb/players/chris-miller-1.html",
        "http://www.sports-reference.com/cfb/players/chris-miller-2.html",
        "http://www.sports-reference.com/cfb/players/chris-miller-3.html",
        "http://www.sports-reference.com/cfb/players/chris-miller-4.html",
        "http://www.sports-reference.com/cfb/players/chris-miller-5.html",
        "http://www.sports-reference.com/cfb/players/jim-miller-2.html",
        "http://www.sports-reference.com/cfb/players/jim-miller-3.html",
        "http://www.sports-reference.com/cfb/players/jim-miller-4.html",
        "http://www.sports-reference.com/cfb/players/jim-miller-5.html",
        "http://www.sports-reference.com/cfb/players/jim-miller-6.html",
        "http://www.sports-reference.com/cfb/players/jim-miller-7.html",
        "http://www.sports-reference.com/cfb/players/jim-miller-8.html",
        "http://www.sports-reference.com/cfb/players/rick-mirer-1.html",
        "http://www.sports-reference.com/cfb/players/scott-mitchell-1.html",
        "http://www.sports-reference.com/cfb/players/scott-mitchell-2.html",
        "http://www.sports-reference.com/cfb/players/scott-mitchell-3.html",
        "http://www.sports-reference.com/cfb/players/joe-montana-1.html",
        "http://www.sports-reference.com/cfb/players/warren-moon-1.html",
        "http://www.sports-reference.com/cfb/players/matt-moore-1.html",
        "http://www.sports-reference.com/cfb/players/matt-moore-2.html",
        "http://www.sports-reference.com/cfb/players/matt-moore-3.html",
        "http://www.sports-reference.com/cfb/players/earl-morrall-1.html",
        "http://www.sports-reference.com/cfb/players/craig-morton-1.html",
        "http://www.sports-reference.com/cfb/players/browning-nagle-1.html",
        "http://www.sports-reference.com/cfb/players/joe-namath-1.html",
        "http://www.sports-reference.com/cfb/players/bill-nelsen-1.html",
        "http://www.sports-reference.com/cfb/players/cam-newton-1.html",
        "http://www.sports-reference.com/cfb/players/gifford-nielsen-1.html",
        "http://www.sports-reference.com/cfb/players/jim-ninowski-1.html",
        "http://www.sports-reference.com/cfb/players/kent-nix-1.html",
        "http://www.sports-reference.com/cfb/players/dan-orlovsky-1.html",
        "http://www.sports-reference.com/cfb/players/kyle-orton-1.html",
        "http://www.sports-reference.com/cfb/players/mike-pagel-1.html",
        "http://www.sports-reference.com/cfb/players/curtis-painter-1.html",
        "http://www.sports-reference.com/cfb/players/carson-palmer-1.html",
        "http://www.sports-reference.com/cfb/players/babe-parilli-1.html",
        "http://www.sports-reference.com/cfb/players/rodney-peete-1.html",
        "http://www.sports-reference.com/cfb/players/steve-pelluer-1.html",
        "http://www.sports-reference.com/cfb/players/chad-pennington-1.html",
        "http://www.sports-reference.com/cfb/players/mike-phipps-1.html",
        "http://www.sports-reference.com/cfb/players/milt-plum-1.html",
        "http://www.sports-reference.com/cfb/players/jake-plummer-1.html",
        "http://www.sports-reference.com/cfb/players/jim-plunkett-1.html",
        "http://www.sports-reference.com/cfb/players/christian-ponder-1.html",
        "http://www.sports-reference.com/cfb/players/brady-quinn-1.html",
        "http://www.sports-reference.com/cfb/players/warren-rabb-1.html",
        "http://www.sports-reference.com/cfb/players/patrick-ramsey-1.html",
        "http://www.sports-reference.com/cfb/players/tim-rattay-1.html",
        "http://www.sports-reference.com/cfb/players/john-reaves-1.html",
        "http://www.sports-reference.com/cfb/players/joe-reed-1.html",
        "http://www.sports-reference.com/cfb/players/joe-reed-2.html",
        "http://www.sports-reference.com/cfb/players/frank-reich-1.html",
        "http://www.sports-reference.com/cfb/players/philip-rivers-1.html",
        "http://www.sports-reference.com/cfb/players/john-roach-1.html",
        "http://www.sports-reference.com/cfb/players/matt-robinson-1.html",
        "http://www.sports-reference.com/cfb/players/matt-robinson-2.html",
        "http://www.sports-reference.com/cfb/players/matt-robinson-3.html",
        "http://www.sports-reference.com/cfb/players/aaron-rodgers-1.html",
        "http://www.sports-reference.com/cfb/players/ben-roethlisberger-1.html",
        "http://www.sports-reference.com/cfb/players/timm-rosenbach-1.html",
        "http://www.sports-reference.com/cfb/players/tj-rubley-1.html",
        "http://www.sports-reference.com/cfb/players/jamarcus-russell-1.html",
        "http://www.sports-reference.com/cfb/players/frank-ryan-1.html",
        "http://www.sports-reference.com/cfb/players/frank-ryan-2.html",
        "http://www.sports-reference.com/cfb/players/matt-ryan-1.html",
        "http://www.sports-reference.com/cfb/players/pat-ryan-1.html",
        "http://www.sports-reference.com/cfb/players/mark-rypien-1.html",
        "http://www.sports-reference.com/cfb/players/mark-sanchez-1.html",
        "http://www.sports-reference.com/cfb/players/jack-scarbath-1.html",
        "http://www.sports-reference.com/cfb/players/matt-schaub-1.html",
        "http://www.sports-reference.com/cfb/players/jay-schroeder-1.html",
        "http://www.sports-reference.com/cfb/players/bobby-scott-1.html",
        "http://www.sports-reference.com/cfb/players/george-shaw-1.html",
        "http://www.sports-reference.com/cfb/players/tom-sherman-1.html",
        "http://www.sports-reference.com/cfb/players/dick-shiner-1.html",
        "http://www.sports-reference.com/cfb/players/heath-shuler-1.html",
        "http://www.sports-reference.com/cfb/players/chris-simms-1.html",
        "http://www.sports-reference.com/cfb/players/akili-smith-1.html",
        "http://www.sports-reference.com/cfb/players/alex-smith-1.html",
        "http://www.sports-reference.com/cfb/players/alex-smith-2.html",
        "http://www.sports-reference.com/cfb/players/alex-smith-3.html",
        "http://www.sports-reference.com/cfb/players/alex-smith-4.html",
        "http://www.sports-reference.com/cfb/players/alex-smith-5.html",
        "http://www.sports-reference.com/cfb/players/alex-smith-6.html",
        "http://www.sports-reference.com/cfb/players/brad-smith-4.html",
        "http://www.sports-reference.com/cfb/players/brad-smith-5.html",
        "http://www.sports-reference.com/cfb/players/brad-smith-1.html",
        "http://www.sports-reference.com/cfb/players/brad-smith-2.html",
        "http://www.sports-reference.com/cfb/players/brad-smith-3.html",
        "http://www.sports-reference.com/cfb/players/norm-snead-1.html",
        "http://www.sports-reference.com/cfb/players/steve-spurrier-1.html",
        "http://www.sports-reference.com/cfb/players/steve-spurrier-2.html",
        "http://www.sports-reference.com/cfb/players/ken-stabler-1.html",
        "http://www.sports-reference.com/cfb/players/matthew-stafford-1.html",
        "http://www.sports-reference.com/cfb/players/roger-staubach-1.html",
        "http://www.sports-reference.com/cfb/players/steve-stenstrom-1.html",
        "http://www.sports-reference.com/cfb/players/kordell-stewart-1.html",
        "http://www.sports-reference.com/cfb/players/john-stofa-1.html",
        "http://www.sports-reference.com/cfb/players/kelly-stouffer-1.html",
        "http://www.sports-reference.com/cfb/players/don-strock-1.html",
        "http://www.sports-reference.com/cfb/players/karl-sweetan-1.html",
        "http://www.sports-reference.com/cfb/players/mike-taliaferro-1.html",
        "http://www.sports-reference.com/cfb/players/ryan-tannehill-1.html",
        "http://www.sports-reference.com/cfb/players/fran-tarkenton-1.html",
        "http://www.sports-reference.com/cfb/players/tim-tebow-1.html",
        "http://www.sports-reference.com/cfb/players/vinny-testaverde-1.html",
        "http://www.sports-reference.com/cfb/players/joe-theismann-1.html",
        "http://www.sports-reference.com/cfb/players/jack-thompson-1.html",
        "http://www.sports-reference.com/cfb/players/richard-todd-1.html",
        "http://www.sports-reference.com/cfb/players/billy-joe-tolliver-1.html",
        "http://www.sports-reference.com/cfb/players/mike-tomczak-1.html",
        "http://www.sports-reference.com/cfb/players/bill-troup-1.html",
        "http://www.sports-reference.com/cfb/players/jack-trudeau-1.html",
        "http://www.sports-reference.com/cfb/players/tom-tupa-1.html",
        "http://www.sports-reference.com/cfb/players/norm-van-brocklin-1.html",
        "http://www.sports-reference.com/cfb/players/alex-van-pelt-1.html",
        "http://www.sports-reference.com/cfb/players/michael-vick-1.html",
        "http://www.sports-reference.com/cfb/players/billy-volek-1.html",
        "http://www.sports-reference.com/cfb/players/billy-wade-1.html",
        "http://www.sports-reference.com/cfb/players/seneca-wallace-1.html",
        "http://www.sports-reference.com/cfb/players/steve-walsh-1.html",
        "http://www.sports-reference.com/cfb/players/andrew-walter-1.html",
        "http://www.sports-reference.com/cfb/players/brandon-weeden-1.html",
        "http://www.sports-reference.com/cfb/players/chris-weinke-1.html",
        "http://www.sports-reference.com/cfb/players/craig-whelihan-1.html",
        "http://www.sports-reference.com/cfb/players/danny-white-1.html",
        "http://www.sports-reference.com/cfb/players/bob-williams-2.html",
        "http://www.sports-reference.com/cfb/players/bob-williams-3.html",
        "http://www.sports-reference.com/cfb/players/bob-williams-4.html",
        "http://www.sports-reference.com/cfb/players/bob-williams-5.html",
        "http://www.sports-reference.com/cfb/players/bob-williams-6.html",
        "http://www.sports-reference.com/cfb/players/doug-williams-1.html",
        "http://www.sports-reference.com/cfb/players/doug-williams-2.html",
        "http://www.sports-reference.com/cfb/players/doug-williams-3.html",
        "http://www.sports-reference.com/cfb/players/doug-williams-4.html",
        "http://www.sports-reference.com/cfb/players/doug-williams-5.html",
        "http://www.sports-reference.com/cfb/players/dave-wilson-1.html",
        "http://www.sports-reference.com/cfb/players/dave-wilson-2.html",
        "http://www.sports-reference.com/cfb/players/dave-wilson-3.html",
        "http://www.sports-reference.com/cfb/players/george-wilson-1.html",
        "http://www.sports-reference.com/cfb/players/george-wilson-2.html",
        "http://www.sports-reference.com/cfb/players/marc-wilson-1.html",
        "http://www.sports-reference.com/cfb/players/marc-wilson-2.html",
        "http://www.sports-reference.com/cfb/players/marc-wilson-3.html",
        "http://www.sports-reference.com/cfb/players/russell-wilson-1.html",
        "http://www.sports-reference.com/cfb/players/al-woodall-1.html",
        "http://www.sports-reference.com/cfb/players/david-woodley-1.html",
        "http://www.sports-reference.com/cfb/players/anthony-wright-1.html",
        "http://www.sports-reference.com/cfb/players/anthony-wright-2.html",
        "http://www.sports-reference.com/cfb/players/anthony-wright-3.html",
        "http://www.sports-reference.com/cfb/players/anthony-wright-4.html",
        "http://www.sports-reference.com/cfb/players/randy-wright-1.html",
        "http://www.sports-reference.com/cfb/players/steve-young-1.html",
        "http://www.sports-reference.com/cfb/players/steve-young-2.html",
        "http://www.sports-reference.com/cfb/players/steve-young-3.html",
        "http://www.sports-reference.com/cfb/players/vince-young-1.html"
    ]

    label_ref = {
            'Year' :      'year',
            'Age' :       'age',
            'Tm' :        'team',
            'Pos' :       'pos',
            'No.' :       'number',
            'G' :         'games_played',
            'GS' :        'games_started',
            'QBrec' :     'rec_in_gs',
            'Cmp' :       'completions',
            'Att' :       'att',
            'Cmp%' :      'completion_percentage',
            'Yds' :       'yds',
            'TD' :        'tds',
            'TD%' :       'td_percentage',
            'Int' :       'ints',
            'Int%' :      'int_percentage',
            'Lng' :       'longest_pass',
            'Y/A' :       'yds_per_att',
            'AY/A' :      'avg_yds_per_att',
            'Y/C' :       'yds_per_comp',
            'Y/G' :       'yds_per_game',
            'Rate' :      'rating',
            'QBR' :       'qbr',
            'Sk' :        'sacked',
            'Sk_Yds' :    'yds_lost_by_sack',
            'NY/A' :      'net_yds_per_att',
            'ANY/A' :     'adj_net_yds_per_att',
            'Sk%' :       'perc_times_sk',
            '4QC' :       'comebacks',
            'GWD' :       'gwds',
            'AV' :        'avg_value'
    }

    def parse(self, response):
        hxs = HtmlXPathSelector(response)
        item = CfbQbItem()
        stat_ref = []

        # Get name
        name = hxs.select('//h1').select('text()').extract()[0].strip()
        item['name'] = name.replace('\.','')

        # Get position
        isQB = False
        pars = hxs.select('//p')
        for p in pars:
            content = str(p.select('text()').extract())
            print content
            if "QB" in content:
                isQB = True

        # Confirm this is for a quarterback
        if isQB == False:
            return;

        print name

        # Get stats
        stat_labels = hxs.select('//table[@id="passing"]/thead/tr/th')
        count = 0
        for label in stat_labels:
            label = label.select('text()').extract()
        if str(label) != "[]":
            stat_ref.append(str(label[0].strip()))
        count += 1
        print stat_ref

        # Count the number of years played
        stats_row = hxs.select('//table[@id="passing"]/tbody/tr')
        num_years = 0
        for row in stats_row:
            num_years += 1
           #print row.select('td').extract()
            print num_years

            # Get the career stats
            stats_row = hxs.select('//table[@id="passing"]/tfoot/tr')
        values = []

        for row in stats_row:
            row_of_stats = row.select('td').extract()
            if("Career" in str(row_of_stats)):
               print row_of_stats
            for field in row_of_stats:
                print field
                # strip td tag
                value = re.search('.*>(.*)<.*', field).group(1).strip()
                values.append(str(value))
        print values

        item['cmpp'] = values[5]
        item['att'] = values[6]
        item['pct'] = values[7]
        item['yds'] = values[8]
        item['ya'] = values[9]
        item['aya'] = values[10]
        item['td'] = values[11]
        item['inter'] = values[12]
        item['rate'] = values[13]
        item['numyrs'] = num_years

        return item
