from scrapy.spider import BaseSpider
from scrapy.selector import HtmlXPathSelector
import re

from qb_scraper.items import QbItem

class QbSpider(BaseSpider):
    name = "pro-football-reference"
    allowed_domains = ["pro-football-reference.com"]
    start_urls = [
            "http://www.pro-football-reference.com/players/A/AdamTo00.htm",
            "http://www.pro-football-reference.com/players/A/AdkiSa00.htm",
            "http://www.pro-football-reference.com/players/A/AikmTr00.htm",
            "http://www.pro-football-reference.com/players/A/AlbeFr00.htm",
            "http://www.pro-football-reference.com/players/A/AllaDo20.htm",
            "http://www.pro-football-reference.com/players/A/AlleEr20.htm",
            "http://www.pro-football-reference.com/players/A/AndeBi21.htm",
            "http://www.pro-football-reference.com/players/A/AndeKe00.htm",
            "http://www.pro-football-reference.com/players/A/ArchDa00.htm",
            "http://www.pro-football-reference.com/players/A/ArriRi00.htm",
            "http://www.pro-football-reference.com/players/A/AustKe20.htm",
            "http://www.pro-football-reference.com/players/A/AvelBo00.htm",
            "http://www.pro-football-reference.com/players/B/BadaRi20.htm",
            "http://www.pro-football-reference.com/players/B/BakeEd00.htm",
            "http://www.pro-football-reference.com/players/B/BakeTe00.htm",
            "http://www.pro-football-reference.com/players/B/BankTo00.htm",
            "http://www.pro-football-reference.com/players/B/BarnJo01.htm",
            "http://www.pro-football-reference.com/players/B/BarnPa20.htm",
            "http://www.pro-football-reference.com/players/B/BarrDa20.htm",
            "http://www.pro-football-reference.com/players/B/BartRi00.htm",
            "http://www.pro-football-reference.com/players/B/BartSt00.htm",
            "http://www.pro-football-reference.com/players/B/BartGr20.htm",
            "http://www.pro-football-reference.com/players/B/BasaBr00.htm",
            "http://www.pro-football-reference.com/players/B/BaugSa00.htm",
            "http://www.pro-football-reference.com/players/B/BeatPe00.htm",
            "http://www.pro-football-reference.com/players/B/BebaGa00.htm",
            "http://www.pro-football-reference.com/players/B/BeckJo00.htm",
            "http://www.pro-football-reference.com/players/B/BellKe00.htm",
            "http://www.pro-football-reference.com/players/B/BenjGu00.htm",
            "http://www.pro-football-reference.com/players/B/BennFr00.htm",
            "http://www.pro-football-reference.com/players/B/BennBe20.htm",
            "http://www.pro-football-reference.com/players/B/BerlBr00.htm",
            "http://www.pro-football-reference.com/players/B/BerrBo00.htm",
            "http://www.pro-football-reference.com/players/B/BertAn20.htm",
            "http://www.pro-football-reference.com/players/B/BethMc00.htm",
            "http://www.pro-football-reference.com/players/B/BeueSt00.htm",
            "http://www.pro-football-reference.com/players/B/BishMi00.htm",
            "http://www.pro-football-reference.com/players/B/BlacTo00.htm",
            "http://www.pro-football-reference.com/players/B/BlakJe00.htm",
            "http://www.pro-football-reference.com/players/B/BlanMa00.htm",
            "http://www.pro-football-reference.com/players/B/BlanGe00.htm",
            "http://www.pro-football-reference.com/players/B/BledDr00.htm",
            "http://www.pro-football-reference.com/players/B/BleiBo20.htm",
            "http://www.pro-football-reference.com/players/B/BlouEd20.htm",
            "http://www.pro-football-reference.com/players/B/BlouJe00.htm",
            "http://www.pro-football-reference.com/players/B/BlunMa00.htm",
            "http://www.pro-football-reference.com/players/B/BollKy00.htm",
            "http://www.pro-football-reference.com/players/B/BollBr00.htm",
            "http://www.pro-football-reference.com/players/B/BonoSt00.htm",
            "http://www.pro-football-reference.com/players/B/BortJo20.htm",
    "http://www.pro-football-reference.com/players/B/BoryMi00.htm",
        "http://www.pro-football-reference.com/players/B/BoumTo00.htm",
        "http://www.pro-football-reference.com/players/B/BracCh20.htm",
        "http://www.pro-football-reference.com/players/B/BradSt20.htm",
        "http://www.pro-football-reference.com/players/B/BradCr20.htm",
        "http://www.pro-football-reference.com/players/B/BradTe00.htm",
        "http://www.pro-football-reference.com/players/B/BradPa21.htm",
        "http://www.pro-football-reference.com/players/B/BranTo00.htm",
        "http://www.pro-football-reference.com/players/B/BratZe00.htm",
        "http://www.pro-football-reference.com/players/B/BreaDo00.htm",
        "http://www.pro-football-reference.com/players/B/BreeAd20.htm",
        "http://www.pro-football-reference.com/players/B/BrigWa20.htm",
        "http://www.pro-football-reference.com/players/B/BrisBu00.htm",
        "http://www.pro-football-reference.com/players/B/BritJo00.htm",
        "http://www.pro-football-reference.com/players/B/BrocDi00.htm",
        "http://www.pro-football-reference.com/players/B/BrodBo00.htm",
        "http://www.pro-football-reference.com/players/B/BrodJo00.htm",
        "http://www.pro-football-reference.com/players/B/BrohBr00.htm",
        "http://www.pro-football-reference.com/players/B/BrohJe00.htm",
        "http://www.pro-football-reference.com/players/B/BrooAa00.htm",
        "http://www.pro-football-reference.com/players/B/BrowCa00.htm",
        "http://www.pro-football-reference.com/players/B/BrowDa00.htm",
        "http://www.pro-football-reference.com/players/B/BrowEd01.htm",
        "http://www.pro-football-reference.com/players/B/BrowJa01.htm",
        "http://www.pro-football-reference.com/players/B/BrowLe00.htm",
        "http://www.pro-football-reference.com/players/B/BrowTr01.htm",
        "http://www.pro-football-reference.com/players/B/BrunMa00.htm",
        "http://www.pro-football-reference.com/players/B/BrunSc00.htm",
        "http://www.pro-football-reference.com/players/B/BuckMi00.htm",
        "http://www.pro-football-reference.com/players/B/BukiRu00.htm",
        "http://www.pro-football-reference.com/players/B/BulgMa00.htm",
        "http://www.pro-football-reference.com/players/B/BullSc00.htm",
        "http://www.pro-football-reference.com/players/B/BurkAd00.htm",
        "http://www.pro-football-reference.com/players/B/BurnEd20.htm",
        "http://www.pro-football-reference.com/players/B/BurrHe00.htm",
        "http://www.pro-football-reference.com/players/B/BuscMi20.htm",
        "http://www.pro-football-reference.com/players/B/BussYo20.htm",
        "http://www.pro-football-reference.com/players/C/CampJi20.htm",
        "http://www.pro-football-reference.com/players/C/CampRi00.htm",
        "http://www.pro-football-reference.com/players/C/CampSc00.htm",
        "http://www.pro-football-reference.com/players/C/CappBi00.htm",
        "http://www.pro-football-reference.com/players/C/CaraGl00.htm",
        "http://www.pro-football-reference.com/players/C/CarlCo00.htm",
        "http://www.pro-football-reference.com/players/C/CarlDe00.htm",
        "http://www.pro-football-reference.com/players/C/CarlJe00.htm",
        "http://www.pro-football-reference.com/players/C/CarpRu00.htm",
        "http://www.pro-football-reference.com/players/C/CartQu00.htm",
        "http://www.pro-football-reference.com/players/C/CartVi00.htm",
        "http://www.pro-football-reference.com/players/C/CasaKe20.htm",
        "http://www.pro-football-reference.com/players/C/CaseEr20.htm",
        "http://www.pro-football-reference.com/players/C/CaseSt00.htm",
        "http://www.pro-football-reference.com/players/C/CavaMa00.htm",
        "http://www.pro-football-reference.com/players/C/CeleBo00.htm",
        "http://www.pro-football-reference.com/players/C/ChanCh00.htm",
        "http://www.pro-football-reference.com/players/C/CherMi00.htm",
        "http://www.pro-football-reference.com/players/C/ChleEd00.htm",
        "http://www.pro-football-reference.com/players/C/ChobMa00.htm",
        "http://www.pro-football-reference.com/players/C/ChriJe20.htm",
        "http://www.pro-football-reference.com/players/C/ChriPa20.htm",
        "http://www.pro-football-reference.com/players/C/CipaLa00.htm",
        "http://www.pro-football-reference.com/players/C/ClarDe02.htm",
        "http://www.pro-football-reference.com/players/C/ClarBr22.htm",
        "http://www.pro-football-reference.com/players/C/ClarWa00.htm",
        "http://www.pro-football-reference.com/players/C/ClatBo00.htm",
        "http://www.pro-football-reference.com/players/C/ClauJi00.htm",
        "http://www.pro-football-reference.com/players/C/ClemCh21.htm",
        "http://www.pro-football-reference.com/players/C/ClemTo20.htm",
        "http://www.pro-football-reference.com/players/C/CochRe20.htm",
        "http://www.pro-football-reference.com/players/C/ColeB.00.htm",
        "http://www.pro-football-reference.com/players/C/CollRe20.htm",
        "http://www.pro-football-reference.com/players/C/CollKe00.htm",
        "http://www.pro-football-reference.com/players/C/CollPa22.htm",
        "http://www.pro-football-reference.com/players/C/CollTo00.htm",
        "http://www.pro-football-reference.com/players/C/CompOg20.htm",
        "http://www.pro-football-reference.com/players/C/ConcJa00.htm",
        "http://www.pro-football-reference.com/players/C/ConeCh00.htm",
        "http://www.pro-football-reference.com/players/C/ConkCa00.htm",
        "http://www.pro-football-reference.com/players/C/CookGr00.htm",
        "http://www.pro-football-reference.com/players/C/CorcKi00.htm",
        "http://www.pro-football-reference.com/players/C/CottRu20.htm",
        "http://www.pro-football-reference.com/players/C/CoucTi00.htm",
        "http://www.pro-football-reference.com/players/C/CoviSc00.htm",
        "http://www.pro-football-reference.com/players/C/CoxxNo20.htm",
        "http://www.pro-football-reference.com/players/C/CraiDa00.htm",
        "http://www.pro-football-reference.com/players/C/CrocJi20.htm",
        "http://www.pro-football-reference.com/players/C/CromJo00.htm",
        "http://www.pro-football-reference.com/players/C/CroyBr00.htm",
        "http://www.pro-football-reference.com/players/C/CulpDa00.htm",
        "http://www.pro-football-reference.com/players/C/CunnRa00.htm",
        "http://www.pro-football-reference.com/players/C/CuozGa00.htm",
        "http://www.pro-football-reference.com/players/C/CureWi00.htm",
        "http://www.pro-football-reference.com/players/D/DancBo20.htm",
        "http://www.pro-football-reference.com/players/D/DaniGa00.htm",
        "http://www.pro-football-reference.com/players/D/DarrDa00.htm",
        "http://www.pro-football-reference.com/players/D/DaveRo01.htm",
        "http://www.pro-football-reference.com/players/D/DaviCo00.htm",
        "http://www.pro-football-reference.com/players/D/DaviAu00.htm",
        "http://www.pro-football-reference.com/players/D/DaviBo00.htm",
        "http://www.pro-football-reference.com/players/D/DawsLe00.htm",
        "http://www.pro-football-reference.com/players/D/DayxEa00.htm",
        "http://www.pro-football-reference.com/players/D/DeanRa00.htm",
        "http://www.pro-football-reference.com/players/D/DebeSt00.htm",
        "http://www.pro-football-reference.com/players/D/DelBJa20.htm",
        "http://www.pro-football-reference.com/players/D/DelGJi00.htm",
        "http://www.pro-football-reference.com/players/D/DelhJa00.htm",
        "http://www.pro-football-reference.com/players/D/DemoBi00.htm",
        "http://www.pro-football-reference.com/players/D/DeMoBo20.htm",
        "http://www.pro-football-reference.com/players/D/DetmKo00.htm",
        "http://www.pro-football-reference.com/players/D/DetmTy00.htm",
        "http://www.pro-football-reference.com/players/D/DevlPa00.htm",
        "http://www.pro-football-reference.com/players/D/DialBe00.htm",
        "http://www.pro-football-reference.com/players/D/DickLy00.htm",
        "http://www.pro-football-reference.com/players/D/DickPa00.htm",
        "http://www.pro-football-reference.com/players/D/DilfTr00.htm",
        "http://www.pro-football-reference.com/players/D/DilsSt00.htm",
        "http://www.pro-football-reference.com/players/D/DilwAn00.htm",
        "http://www.pro-football-reference.com/players/D/DimiTo00.htm",
        "http://www.pro-football-reference.com/players/D/DiviJo00.htm",
        "http://www.pro-football-reference.com/players/D/DixoDe00.htm",
        "http://www.pro-football-reference.com/players/D/DomrMa00.htm",
        "http://www.pro-football-reference.com/players/D/DoncBi00.htm",
        "http://www.pro-football-reference.com/players/D/DoroAl00.htm",
        "http://www.pro-football-reference.com/players/D/DorsKe00.htm",
        "http://www.pro-football-reference.com/players/D/DougBo00.htm",
        "http://www.pro-football-reference.com/players/D/DowlBr00.htm",
        "http://www.pro-football-reference.com/players/D/DrucJi00.htm",
        "http://www.pro-football-reference.com/players/D/DublTo00.htm",
        "http://www.pro-football-reference.com/players/D/DufeJo00.htm",
        "http://www.pro-football-reference.com/players/D/DuncMa20.htm",
        "http://www.pro-football-reference.com/players/D/DuncRa00.htm",
        "http://www.pro-football-reference.com/players/D/DuniTo20.htm",
        "http://www.pro-football-reference.com/players/E/EasoTo00.htm",
        "http://www.pro-football-reference.com/players/E/EatoVi20.htm",
        "http://www.pro-football-reference.com/players/E/EikeCh20.htm",
        "http://www.pro-football-reference.com/players/E/ElkiMi00.htm",
        "http://www.pro-football-reference.com/players/E/ElwaJo00.htm",
        "http://www.pro-football-reference.com/players/E/EndeNa00.htm",
        "http://www.pro-football-reference.com/players/E/EnisHu00.htm",
        "http://www.pro-football-reference.com/players/E/EnkeFr20.htm",
        "http://www.pro-football-reference.com/players/E/EricCr00.htm",
        "http://www.pro-football-reference.com/players/E/ErnsMi00.htm",
        "http://www.pro-football-reference.com/players/E/EsiaBo00.htm",
        "http://www.pro-football-reference.com/players/E/EspiAl21.htm",
        "http://www.pro-football-reference.com/players/E/EtchSa00.htm",
        "http://www.pro-football-reference.com/players/E/EvanVi00.htm",
        "http://www.pro-football-reference.com/players/E/EverJi00.htm",
        "http://www.pro-football-reference.com/players/F/FarrTo20.htm",
        "http://www.pro-football-reference.com/players/F/FasaRa00.htm",
        "http://www.pro-football-reference.com/players/F/FavrBr00.htm",
        "http://www.pro-football-reference.com/players/F/FeelA.00.htm",
        "http://www.pro-football-reference.com/players/F/FergJo00.htm",
        "http://www.pro-football-reference.com/players/F/FerrVi00.htm",
        "http://www.pro-football-reference.com/players/F/FiedJa00.htm",
        "http://www.pro-football-reference.com/players/F/FinkJi00.htm",
        "http://www.pro-football-reference.com/players/F/FlicTo00.htm",
        "http://www.pro-football-reference.com/players/F/FlorTo00.htm",
        "http://www.pro-football-reference.com/players/F/FlowDi20.htm",
        "http://www.pro-football-reference.com/players/F/FlutDo00.htm",
        "http://www.pro-football-reference.com/players/F/FoleGl00.htm",
        "http://www.pro-football-reference.com/players/F/FolmBr20.htm",
        "http://www.pro-football-reference.com/players/F/FourJo00.htm",
        "http://www.pro-football-reference.com/players/F/FoutDa00.htm",
        "http://www.pro-football-reference.com/players/F/FranJe20.htm",
        "http://www.pro-football-reference.com/players/F/FranJo20.htm",
        "http://www.pro-football-reference.com/players/F/FreiJe20.htm",
        "http://www.pro-football-reference.com/players/F/FreiJe00.htm",
        "http://www.pro-football-reference.com/players/F/FrerGu00.htm",
        "http://www.pro-football-reference.com/players/F/FrieJo00.htm",
        "http://www.pro-football-reference.com/players/F/FryeCh00.htm",
        "http://www.pro-football-reference.com/players/F/FullSt00.htm",
        "http://www.pro-football-reference.com/players/F/FurrWi00.htm",
        "http://www.pro-football-reference.com/players/F/FusiCh00.htm",
        "http://www.pro-football-reference.com/players/G/GabrRo00.htm",
        "http://www.pro-football-reference.com/players/G/GaffJi20.htm",
        "http://www.pro-football-reference.com/players/G/GaglBo00.htm",
        "http://www.pro-football-reference.com/players/G/GaliAr20.htm",
        "http://www.pro-football-reference.com/players/G/GallCh00.htm",
        "http://www.pro-football-reference.com/players/G/GalvJo20.htm",
        "http://www.pro-football-reference.com/players/G/GambBo20.htm",
        "http://www.pro-football-reference.com/players/G/GannRi00.htm",
        "http://www.pro-football-reference.com/players/G/GarcJe00.htm",
        "http://www.pro-football-reference.com/players/G/GarnBi20.htm",
        "http://www.pro-football-reference.com/players/G/GarrDa00.htm",
        "http://www.pro-football-reference.com/players/G/GarrBo20.htm",
        "http://www.pro-football-reference.com/players/G/GarrJa00.htm",
        "http://www.pro-football-reference.com/players/G/GarzSa20.htm",
        "http://www.pro-football-reference.com/players/G/GaulDo00.htm",
        "http://www.pro-football-reference.com/players/G/GaynDo20.htm",
        "http://www.pro-football-reference.com/players/G/GelbSt00.htm",
        "http://www.pro-football-reference.com/players/G/GeorJe00.htm",
        "http://www.pro-football-reference.com/players/G/GermJo00.htm",
        "http://www.pro-football-reference.com/players/G/GibbSo00.htm",
        "http://www.pro-football-reference.com/players/G/GiftWa20.htm",
        "http://www.pro-football-reference.com/players/G/GilbGa00.htm",
        "http://www.pro-football-reference.com/players/G/GillJo00.htm",
        "http://www.pro-football-reference.com/players/G/GillWi21.htm",
        "http://www.pro-football-reference.com/players/G/GilmHa00.htm",
        "http://www.pro-football-reference.com/players/G/GlacSc00.htm",
        "http://www.pro-football-reference.com/players/G/GlenBi20.htm",
        "http://www.pro-football-reference.com/players/G/GoebBr00.htm",
        "http://www.pro-football-reference.com/players/G/GolsJe00.htm",
        "http://www.pro-football-reference.com/players/G/GonzPe00.htm",
        "http://www.pro-football-reference.com/players/G/GovePa20.htm",
        "http://www.pro-football-reference.com/players/G/GrafNe00.htm",
        "http://www.pro-football-reference.com/players/G/GrahKe00.htm",
        "http://www.pro-football-reference.com/players/G/GrahOt00.htm",
        "http://www.pro-football-reference.com/players/G/GrayQu00.htm",
        "http://www.pro-football-reference.com/players/G/GrazTo00.htm",
        "http://www.pro-football-reference.com/players/G/GrbaEl00.htm",
        "http://www.pro-football-reference.com/players/G/GreeCh00.htm",
        "http://www.pro-football-reference.com/players/G/GreeJo00.htm",
        "http://www.pro-football-reference.com/players/G/GreeTr00.htm",
        "http://www.pro-football-reference.com/players/G/GreeTo20.htm",
        "http://www.pro-football-reference.com/players/G/GreiCh00.htm",
        "http://www.pro-football-reference.com/players/G/GrieBo00.htm",
        "http://www.pro-football-reference.com/players/G/GrieBr00.htm",
        "http://www.pro-football-reference.com/players/G/GrifGl00.htm",
        "http://www.pro-football-reference.com/players/G/GrogSt00.htm",
        "http://www.pro-football-reference.com/players/G/GrosLe00.htm",
        "http://www.pro-football-reference.com/players/G/GrosRe00.htm",
        "http://www.pro-football-reference.com/players/G/GudmSc20.htm",
        "http://www.pro-football-reference.com/players/G/GuglRa00.htm",
        "http://www.pro-football-reference.com/players/G/GutiMa00.htm",
        "http://www.pro-football-reference.com/players/H/HadePa00.htm",
        "http://www.pro-football-reference.com/players/H/HadlJo00.htm",
        "http://www.pro-football-reference.com/players/H/HallAn00.htm",
        "http://www.pro-football-reference.com/players/H/HallGa00.htm",
        "http://www.pro-football-reference.com/players/H/HallMa00.htm",
        "http://www.pro-football-reference.com/players/H/HallSh20.htm",
        "http://www.pro-football-reference.com/players/H/HaluJi20.htm",
        "http://www.pro-football-reference.com/players/H/HamdGi00.htm",
        "http://www.pro-football-reference.com/players/H/HamiJo20.htm",
        "http://www.pro-football-reference.com/players/H/HammKi00.htm",
        "http://www.pro-football-reference.com/players/H/HaniCa00.htm",
        "http://www.pro-football-reference.com/players/H/HanrTe00.htm",
        "http://www.pro-football-reference.com/players/H/HarbJi00.htm",
        "http://www.pro-football-reference.com/players/H/HardJi00.htm",
        "http://www.pro-football-reference.com/players/H/HargEd00.htm",
        "http://www.pro-football-reference.com/players/H/HarnCh00.htm",
        "http://www.pro-football-reference.com/players/H/HarrJo00.htm",
        "http://www.pro-football-reference.com/players/H/HarrJa01.htm",
        "http://www.pro-football-reference.com/players/H/HartJi00.htm",
        "http://www.pro-football-reference.com/players/H/HartLe00.htm",
        "http://www.pro-football-reference.com/players/H/HartMa20.htm",
        "http://www.pro-football-reference.com/players/H/HassTi00.htm",
        "http://www.pro-football-reference.com/players/H/HeatSt20.htm",
        "http://www.pro-football-reference.com/players/H/HebeBo00.htm",
        "http://www.pro-football-reference.com/players/H/HedbRa00.htm",
        "http://www.pro-football-reference.com/players/H/HeinDo00.htm",
        "http://www.pro-football-reference.com/players/H/HeldPa20.htm",
        "http://www.pro-football-reference.com/players/H/HennDa00.htm",
        "http://www.pro-football-reference.com/players/H/HensDr00.htm",
        "http://www.pro-football-reference.com/players/H/HerrGe00.htm",
        "http://www.pro-football-reference.com/players/H/HerrMa00.htm",
        "http://www.pro-football-reference.com/players/H/HertRo20.htm",
        "http://www.pro-football-reference.com/players/H/HewkBo20.htm",
        "http://www.pro-football-reference.com/players/H/HilgRu00.htm",
        "http://www.pro-football-reference.com/players/H/HillKi00.htm",
        "http://www.pro-football-reference.com/players/H/HippEr00.htm",
        "http://www.pro-football-reference.com/players/H/HirsBu20.htm",
        "http://www.pro-football-reference.com/players/H/HobeBi00.htm",
        "http://www.pro-football-reference.com/players/H/HodsTo00.htm",
        "http://www.pro-football-reference.com/players/H/HogeGa00.htm",
        "http://www.pro-football-reference.com/players/H/HoheMi20.htm",
        "http://www.pro-football-reference.com/players/H/HolcKe00.htm",
        "http://www.pro-football-reference.com/players/H/HoldMi20.htm",
        "http://www.pro-football-reference.com/players/H/HollDo00.htm",
        "http://www.pro-football-reference.com/players/H/HollKe20.htm",
        "http://www.pro-football-reference.com/players/H/HollBo00.htm",
        "http://www.pro-football-reference.com/players/H/HonsTo20.htm",
        "http://www.pro-football-reference.com/players/H/HornDi20.htm",
        "http://www.pro-football-reference.com/players/H/HornDo00.htm",
        "http://www.pro-football-reference.com/players/H/HornMa20.htm",
        "http://www.pro-football-reference.com/players/H/HostJe00.htm",
        "http://www.pro-football-reference.com/players/H/HoyiBo00.htm",
        "http://www.pro-football-reference.com/players/H/HuarBr00.htm",
        "http://www.pro-football-reference.com/players/H/HuarDa00.htm",
        "http://www.pro-football-reference.com/players/H/HuarJo00.htm",
        "http://www.pro-football-reference.com/players/H/HudsDo20.htm",
        "http://www.pro-football-reference.com/players/H/HuffGa00.htm",
        "http://www.pro-football-reference.com/players/H/HufnJo00.htm",
        "http://www.pro-football-reference.com/players/H/HummDa00.htm",
        "http://www.pro-football-reference.com/players/H/HumpBu00.htm",
        "http://www.pro-football-reference.com/players/H/HumpSt00.htm",
        "http://www.pro-football-reference.com/players/H/HuntSc00.htm",
        "http://www.pro-football-reference.com/players/H/HusaTo20.htm",
        "http://www.pro-football-reference.com/players/H/HutcBi20.htm",
        "http://www.pro-football-reference.com/players/H/HutcCh00.htm",
        "http://www.pro-football-reference.com/players/I/IngrKe20.htm",
        "http://www.pro-football-reference.com/players/I/IzoxGe00.htm",
        "http://www.pro-football-reference.com/players/J/JackJa01.htm",
        "http://www.pro-football-reference.com/players/J/JacoJa20.htm",
        "http://www.pro-football-reference.com/players/J/JamiDi00.htm",
        "http://www.pro-football-reference.com/players/J/JawoRo00.htm",
        "http://www.pro-football-reference.com/players/J/JaynDa00.htm",
        "http://www.pro-football-reference.com/players/J/JeffNe00.htm",
        "http://www.pro-football-reference.com/players/J/JemaJi20.htm",
        "http://www.pro-football-reference.com/players/J/JoacSt20.htm",
        "http://www.pro-football-reference.com/players/J/JohnAl20.htm",
        "http://www.pro-football-reference.com/players/J/JohnBr00.htm",
        "http://www.pro-football-reference.com/players/J/JohnCh02.htm",
        "http://www.pro-football-reference.com/players/J/JohnDo00.htm",
        "http://www.pro-football-reference.com/players/J/JohnGi20.htm",
        "http://www.pro-football-reference.com/players/J/JohnRa00.htm",
        "http://www.pro-football-reference.com/players/J/JohnRo00.htm",
        "http://www.pro-football-reference.com/players/J/JoneBe00.htm",
        "http://www.pro-football-reference.com/players/J/JoneJ.00.htm",
        "http://www.pro-football-reference.com/players/J/JoneJu00.htm",
        "http://www.pro-football-reference.com/players/J/JoycBi20.htm",
        "http://www.pro-football-reference.com/players/J/JurgSo00.htm",
        "http://www.pro-football-reference.com/players/J/JustPa00.htm",
        "http://www.pro-football-reference.com/players/K/KafkMi00.htm",
        "http://www.pro-football-reference.com/players/K/KaneDa00.htm",
        "http://www.pro-football-reference.com/players/K/KappJo00.htm",
        "http://www.pro-football-reference.com/players/K/KarcKe00.htm",
        "http://www.pro-football-reference.com/players/K/KarnAb20.htm",
        "http://www.pro-football-reference.com/players/K/KeckVa00.htm",
        "http://www.pro-football-reference.com/players/K/KeenRa20.htm",
        "http://www.pro-football-reference.com/players/K/KeenCa00.htm",
        "http://www.pro-football-reference.com/players/K/KeitGa00.htm",
        "http://www.pro-football-reference.com/players/K/KellMi21.htm",
        "http://www.pro-football-reference.com/players/K/KellJe21.htm",
        "http://www.pro-football-reference.com/players/K/KellJi00.htm",
        "http://www.pro-football-reference.com/players/K/KempJa00.htm",
        "http://www.pro-football-reference.com/players/K/KempJe00.htm",
        "http://www.pro-football-reference.com/players/K/KennTo00.htm",
        "http://www.pro-football-reference.com/players/K/KennBi00.htm",
        "http://www.pro-football-reference.com/players/K/KerkGa20.htm",
        "http://www.pro-football-reference.com/players/K/KerrMi00.htm",
        "http://www.pro-football-reference.com/players/K/KielBl00.htm",
        "http://www.pro-football-reference.com/players/K/KilmBi00.htm",
        "http://www.pro-football-reference.com/players/K/KingSh00.htm",
        "http://www.pro-football-reference.com/players/K/KingKl00.htm",
        "http://www.pro-football-reference.com/players/K/KirkMi00.htm",
        "http://www.pro-football-reference.com/players/K/KitnJo00.htm",
        "http://www.pro-football-reference.com/players/K/KittKu00.htm",
        "http://www.pro-football-reference.com/players/K/KleiPe20.htm",
        "http://www.pro-football-reference.com/players/K/KlinDa00.htm",
        "http://www.pro-football-reference.com/players/K/KlosDo20.htm",
        "http://www.pro-football-reference.com/players/K/KnafGr20.htm",
        "http://www.pro-football-reference.com/players/K/KnapJe20.htm",
        "http://www.pro-football-reference.com/players/K/KnoxRo20.htm",
        "http://www.pro-football-reference.com/players/K/KobrMi20.htm",
        "http://www.pro-football-reference.com/players/K/KoflMa00.htm",
        "http://www.pro-football-reference.com/players/K/KokeMi20.htm",
        "http://www.pro-football-reference.com/players/K/KomlJe00.htm",
        "http://www.pro-football-reference.com/players/K/KosaBe00.htm",
        "http://www.pro-football-reference.com/players/K/KramEr00.htm",
        "http://www.pro-football-reference.com/players/K/KramTo00.htm",
        "http://www.pro-football-reference.com/players/K/KrenCr00.htm",
        "http://www.pro-football-reference.com/players/K/KresEr00.htm",
        "http://www.pro-football-reference.com/players/K/KrieDa00.htm",
        "http://www.pro-football-reference.com/players/K/KrucMi00.htm",
        "http://www.pro-football-reference.com/players/K/KsioJo20.htm",
        "http://www.pro-football-reference.com/players/K/KubiGa00.htm",
        "http://www.pro-football-reference.com/players/K/KupcIr20.htm",
        "http://www.pro-football-reference.com/players/K/KuppCr20.htm",
        "http://www.pro-football-reference.com/players/L/LainPo20.htm",
        "http://www.pro-football-reference.com/players/L/LamoDa00.htm",
        "http://www.pro-football-reference.com/players/L/LandGr00.htm",
        "http://www.pro-football-reference.com/players/L/LaneGa00.htm",
        "http://www.pro-football-reference.com/players/L/LarsPa00.htm",
        "http://www.pro-football-reference.com/players/L/LaufBa00.htm",
        "http://www.pro-football-reference.com/players/L/LawrLa00.htm",
        "http://www.pro-football-reference.com/players/L/LaynBo00.htm",
        "http://www.pro-football-reference.com/players/L/LeafRy00.htm",
        "http://www.pro-football-reference.com/players/L/LeahBo00.htm",
        "http://www.pro-football-reference.com/players/L/LeBaEd00.htm",
        "http://www.pro-football-reference.com/players/L/LeClJi00.htm",
        "http://www.pro-football-reference.com/players/L/LedyHa20.htm",
        "http://www.pro-football-reference.com/players/L/LeexBe20.htm",
        "http://www.pro-football-reference.com/players/L/LeexBo00.htm",
        "http://www.pro-football-reference.com/players/L/LeexJa00.htm",
        "http://www.pro-football-reference.com/players/L/LeFeDa00.htm",
        "http://www.pro-football-reference.com/players/L/LeFoCl20.htm",
        "http://www.pro-football-reference.com/players/L/LeggDa20.htm",
        "http://www.pro-football-reference.com/players/L/LemmBr00.htm",
        "http://www.pro-football-reference.com/players/L/LemoCl00.htm",
        "http://www.pro-football-reference.com/players/L/LewiDa22.htm",
        "http://www.pro-football-reference.com/players/L/LewiJe01.htm",
        "http://www.pro-football-reference.com/players/L/LiscRu00.htm",
        "http://www.pro-football-reference.com/players/L/LiskPe00.htm",
        "http://www.pro-football-reference.com/players/L/LiviMi00.htm",
        "http://www.pro-football-reference.com/players/L/LomaNe00.htm",
        "http://www.pro-football-reference.com/players/L/LongCh00.htm",
        "http://www.pro-football-reference.com/players/L/LongJo20.htm",
        "http://www.pro-football-reference.com/players/L/LongCl00.htm",
        "http://www.pro-football-reference.com/players/L/LookDe00.htm",
        "http://www.pro-football-reference.com/players/L/LoreJa00.htm",
        "http://www.pro-football-reference.com/players/L/LosmJ.00.htm",
        "http://www.pro-football-reference.com/players/L/LoydMi00.htm",
        "http://www.pro-football-reference.com/players/L/LucaRa00.htm",
        "http://www.pro-football-reference.com/players/L/LucaRi00.htm",
        "http://www.pro-football-reference.com/players/L/LuckOl00.htm",
        "http://www.pro-football-reference.com/players/L/LuckTe00.htm",
        "http://www.pro-football-reference.com/players/L/LuckSi00.htm",
        "http://www.pro-football-reference.com/players/L/LujaJo00.htm",
        "http://www.pro-football-reference.com/players/L/LuthEd00.htm",
        "http://www.pro-football-reference.com/players/L/LytlMa00.htm",
        "http://www.pro-football-reference.com/players/M/MachMi00.htm",
        "http://www.pro-football-reference.com/players/M/MackKy00.htm",
        "http://www.pro-football-reference.com/players/M/MackBi20.htm",
        "http://www.pro-football-reference.com/players/M/MaddTo00.htm",
        "http://www.pro-football-reference.com/players/M/MahrLo20.htm",
        "http://www.pro-football-reference.com/players/M/MajkDo00.htm",
        "http://www.pro-football-reference.com/players/M/MallRa20.htm",
        "http://www.pro-football-reference.com/players/M/MaloMa00.htm",
        "http://www.pro-football-reference.com/players/M/MangMa20.htm",
        "http://www.pro-football-reference.com/players/M/MannAr00.htm",
        "http://www.pro-football-reference.com/players/M/ManuDa20.htm",
        "http://www.pro-football-reference.com/players/M/MaraGa00.htm",
        "http://www.pro-football-reference.com/players/M/MarcTe20.htm",
        "http://www.pro-football-reference.com/players/M/MariDa00.htm",
        "http://www.pro-football-reference.com/players/M/MariTo00.htm",
        "http://www.pro-football-reference.com/players/M/MarsRa21.htm",
        "http://www.pro-football-reference.com/players/M/MartIn00.htm",
        "http://www.pro-football-reference.com/players/M/MartJa00.htm",
        "http://www.pro-football-reference.com/players/M/MartTe00.htm",
        "http://www.pro-football-reference.com/players/M/MastBe20.htm",
        "http://www.pro-football-reference.com/players/M/MathBr00.htm",
        "http://www.pro-football-reference.com/players/M/MattSh00.htm",
        "http://www.pro-football-reference.com/players/M/MattSt00.htm",
        "http://www.pro-football-reference.com/players/M/MaucMa00.htm",
        "http://www.pro-football-reference.com/players/M/MayxDe20.htm",
        "http://www.pro-football-reference.com/players/M/MaysDa00.htm",
        "http://www.pro-football-reference.com/players/M/McCaJo23.htm",
        "http://www.pro-football-reference.com/players/M/McClBr20.htm",
        "http://www.pro-football-reference.com/players/M/McCoJo00.htm",
        "http://www.pro-football-reference.com/players/M/McCoJo01.htm",
        "http://www.pro-football-reference.com/players/M/McDoPa00.htm",
        "http://www.pro-football-reference.com/players/M/McGeSt00.htm",
        "http://www.pro-football-reference.com/players/M/McGuMo20.htm",
        "http://www.pro-football-reference.com/players/M/McGwDa00.htm",
        "http://www.pro-football-reference.com/players/M/McHaLa00.htm",
        "http://www.pro-football-reference.com/players/M/McIvRi20.htm",
        "http://www.pro-football-reference.com/players/M/McMaJi00.htm",
        "http://www.pro-football-reference.com/players/M/McMaMi00.htm",
        "http://www.pro-football-reference.com/players/M/McNaDo00.htm",
        "http://www.pro-football-reference.com/players/M/McNaSt00.htm",
        "http://www.pro-football-reference.com/players/M/McNeRe00.htm",
        "http://www.pro-football-reference.com/players/M/McNoCa00.htm",
        "http://www.pro-football-reference.com/players/M/McQuKi00.htm",
        "http://www.pro-football-reference.com/players/M/MereDo00.htm",
        "http://www.pro-football-reference.com/players/M/MeyeRo00.htm",
        "http://www.pro-football-reference.com/players/M/MikoPe20.htm",
        "http://www.pro-football-reference.com/players/M/MilaDo00.htm",
        "http://www.pro-football-reference.com/players/M/MilaSc00.htm",
        "http://www.pro-football-reference.com/players/M/MillHu00.htm",
        "http://www.pro-football-reference.com/players/M/MillCh00.htm",
        "http://www.pro-football-reference.com/players/M/MillJi00.htm",
        "http://www.pro-football-reference.com/players/M/MillLa20.htm",
        "http://www.pro-football-reference.com/players/M/MillMa00.htm",
        "http://www.pro-football-reference.com/players/M/MillMa20.htm",
        "http://www.pro-football-reference.com/players/M/MillRo01.htm",
        "http://www.pro-football-reference.com/players/M/MilsCh20.htm",
        "http://www.pro-football-reference.com/players/M/MiodEd20.htm",
        "http://www.pro-football-reference.com/players/M/MiraGe00.htm",
        "http://www.pro-football-reference.com/players/M/MireRi00.htm",
        "http://www.pro-football-reference.com/players/M/MitcSc00.htm",
        "http://www.pro-football-reference.com/players/M/MontTo20.htm",
        "http://www.pro-football-reference.com/players/M/MontJo01.htm",
        "http://www.pro-football-reference.com/players/M/MoonWa00.htm",
        "http://www.pro-football-reference.com/players/M/MoorKe02.htm",
        "http://www.pro-football-reference.com/players/M/MoorSh00.htm",
        "http://www.pro-football-reference.com/players/M/MoreMo00.htm",
        "http://www.pro-football-reference.com/players/M/MoroMi00.htm",
        "http://www.pro-football-reference.com/players/M/MorrEa00.htm",
        "http://www.pro-football-reference.com/players/M/MorrDe00.htm",
        "http://www.pro-football-reference.com/players/M/MortCr00.htm",
        "http://www.pro-football-reference.com/players/M/MossPe20.htm",
        "http://www.pro-football-reference.com/players/M/MunnGe20.htm",
        "http://www.pro-football-reference.com/players/M/MunsBi00.htm",
        "http://www.pro-football-reference.com/players/M/MusgBi00.htm",
        "http://www.pro-football-reference.com/players/M/MyerSt00.htm",
        "http://www.pro-football-reference.com/players/M/MyerTo00.htm",
        "http://www.pro-football-reference.com/players/N/NageRa20.htm",
        "http://www.pro-football-reference.com/players/N/NaglBr00.htm",
        "http://www.pro-football-reference.com/players/N/NallCr00.htm",
        "http://www.pro-football-reference.com/players/N/NamaJo00.htm",
        "http://www.pro-football-reference.com/players/N/NapoBo00.htm",
        "http://www.pro-football-reference.com/players/N/NavaJo00.htm",
        "http://www.pro-football-reference.com/players/N/NelsBi00.htm",
        "http://www.pro-football-reference.com/players/N/NemeSt20.htm",
        "http://www.pro-football-reference.com/players/N/NeuhRi20.htm",
        "http://www.pro-football-reference.com/players/N/NielGi00.htm",
        "http://www.pro-football-reference.com/players/N/NileJe20.htm",
        "http://www.pro-football-reference.com/players/N/NinoJi00.htm",
        "http://www.pro-football-reference.com/players/N/NixxKe00.htm",
        "http://www.pro-football-reference.com/players/N/NofsTe00.htm",
        "http://www.pro-football-reference.com/players/N/NoriRe20.htm",
        "http://www.pro-football-reference.com/players/N/NormDi20.htm",
        "http://www.pro-football-reference.com/players/N/NorrDa20.htm",
        "http://www.pro-football-reference.com/players/N/NorsMi20.htm",
        "http://www.pro-football-reference.com/players/N/NortRi00.htm",
        "http://www.pro-football-reference.com/players/N/NottMi00.htm",
        "http://www.pro-football-reference.com/players/N/NugeTe20.htm",
        "http://www.pro-football-reference.com/players/N/NullKe00.htm",
        "http://www.pro-football-reference.com/players/N/NussDo00.htm",
        "http://www.pro-football-reference.com/players/O/OBriDa21.htm",
        "http://www.pro-football-reference.com/players/O/OBriKe00.htm",
        "http://www.pro-football-reference.com/players/O/OConKe00.htm",
        "http://www.pro-football-reference.com/players/O/OConTo00.htm",
        "http://www.pro-football-reference.com/players/O/ODonNe00.htm",
        "http://www.pro-football-reference.com/players/O/OMalTo20.htm",
        "http://www.pro-football-reference.com/players/O/ORouCh20.htm",
        "http://www.pro-football-reference.com/players/O/OSulJ.00.htm",
        "http://www.pro-football-reference.com/players/O/OlanCl00.htm",
        "http://www.pro-football-reference.com/players/O/OlivVi20.htm",
        "http://www.pro-football-reference.com/players/O/OsieSa20.htm",
        "http://www.pro-football-reference.com/players/O/OwenTo00.htm",
        "http://www.pro-football-reference.com/players/P/PageMi00.htm",
        "http://www.pro-football-reference.com/players/P/PainCu00.htm",
        "http://www.pro-football-reference.com/players/P/PalkTy00.htm",
        "http://www.pro-football-reference.com/players/P/PalmJe00.htm",
        "http://www.pro-football-reference.com/players/P/PalmJo20.htm",
        "http://www.pro-football-reference.com/players/P/PancDo20.htm",
        "http://www.pro-football-reference.com/players/P/PapaNi00.htm",
        "http://www.pro-football-reference.com/players/P/PariBa00.htm",
        "http://www.pro-football-reference.com/players/P/PastDa00.htm",
        "http://www.pro-football-reference.com/players/P/PastCh00.htm",
        "http://www.pro-football-reference.com/players/P/PatrFr00.htm",
        "http://www.pro-football-reference.com/players/P/PaytSe20.htm",
        "http://www.pro-football-reference.com/players/P/PearPa20.htm",
        "http://www.pro-football-reference.com/players/P/PeasBr00.htm",
        "http://www.pro-football-reference.com/players/P/PedeDo00.htm",
        "http://www.pro-football-reference.com/players/P/PeetRo00.htm",
        "http://www.pro-football-reference.com/players/P/PellSt00.htm",
        "http://www.pro-football-reference.com/players/P/PennCh01.htm",
        "http://www.pro-football-reference.com/players/P/PenrCr00.htm",
        "http://www.pro-football-reference.com/players/P/PerrMi20.htm",
        "http://www.pro-football-reference.com/players/P/PhilTo00.htm",
        "http://www.pro-football-reference.com/players/P/PhipMi00.htm",
        "http://www.pro-football-reference.com/players/P/PickCo00.htm",
        "http://www.pro-football-reference.com/players/P/PikeTo00.htm",
        "http://www.pro-football-reference.com/players/P/PisaJo00.htm",
        "http://www.pro-football-reference.com/players/P/PisaSt00.htm",
        "http://www.pro-football-reference.com/players/P/PlumMi00.htm",
        "http://www.pro-football-reference.com/players/P/PlumJa00.htm",
        "http://www.pro-football-reference.com/players/P/PlunJi00.htm",
        "http://www.pro-football-reference.com/players/P/PortJo01.htm",
        "http://www.pro-football-reference.com/players/P/PtacBo20.htm",
        "http://www.pro-football-reference.com/players/Q/QuarBe20.htm",
        "http://www.pro-football-reference.com/players/Q/QuinJo00.htm",
        "http://www.pro-football-reference.com/players/Q/QuinMi00.htm",
        "http://www.pro-football-reference.com/players/R/RabbWa00.htm",
        "http://www.pro-football-reference.com/players/R/RaexMi00.htm",
        "http://www.pro-football-reference.com/players/R/RagoDa00.htm",
        "http://www.pro-football-reference.com/players/R/RakeLa00.htm",
        "http://www.pro-football-reference.com/players/R/RamsPa00.htm",
        "http://www.pro-football-reference.com/players/R/RamsSt00.htm",
        "http://www.pro-football-reference.com/players/R/RamsTo00.htm",
        "http://www.pro-football-reference.com/players/R/RankWa20.htm",
        "http://www.pro-football-reference.com/players/R/RatlBr00.htm",
        "http://www.pro-football-reference.com/players/R/RattTi00.htm",
        "http://www.pro-football-reference.com/players/R/RattGe00.htm",
        "http://www.pro-football-reference.com/players/R/RaucJo20.htm",
        "http://www.pro-football-reference.com/players/R/ReavJo00.htm",
        "http://www.pro-football-reference.com/players/R/RedmCh00.htm",
        "http://www.pro-football-reference.com/players/R/ReedJo00.htm",
        "http://www.pro-football-reference.com/players/R/ReedMa20.htm",
        "http://www.pro-football-reference.com/players/R/ReicFr00.htm",
        "http://www.pro-football-reference.com/players/R/ReynM.00.htm",
        "http://www.pro-football-reference.com/players/R/RhomJe00.htm",
        "http://www.pro-football-reference.com/players/R/RichBu00.htm",
        "http://www.pro-football-reference.com/players/R/RichWa00.htm",
        "http://www.pro-football-reference.com/players/R/RickPa20.htm",
        "http://www.pro-football-reference.com/players/R/RiorTi20.htm",
        "http://www.pro-football-reference.com/players/R/RishAl20.htm",
        "http://www.pro-football-reference.com/players/R/RitcJa20.htm",
        "http://www.pro-football-reference.com/players/R/RoacJo00.htm",
        "http://www.pro-football-reference.com/players/R/RobeAr00.htm",
        "http://www.pro-football-reference.com/players/R/RobiMa01.htm",
        "http://www.pro-football-reference.com/players/R/RobiTo20.htm",
        "http://www.pro-football-reference.com/players/R/RobiZa00.htm",
        "http://www.pro-football-reference.com/players/R/RomaSt00.htm",
        "http://www.pro-football-reference.com/players/R/RootJi20.htm",
        "http://www.pro-football-reference.com/players/R/RoseTi00.htm",
        "http://www.pro-football-reference.com/players/R/RoseSa00.htm",
        "http://www.pro-football-reference.com/players/R/RoteTo00.htm",
        "http://www.pro-football-reference.com/players/R/RoweJe00.htm",
        "http://www.pro-football-reference.com/players/R/RubbEd20.htm",
        "http://www.pro-football-reference.com/players/R/RublTJ00.htm",
        "http://www.pro-football-reference.com/players/R/RussBe00.htm",
        "http://www.pro-football-reference.com/players/R/RussJa00.htm",
        "http://www.pro-football-reference.com/players/R/RutkEd00.htm",
        "http://www.pro-football-reference.com/players/R/RutlJe00.htm",
        "http://www.pro-football-reference.com/players/R/RyanFr00.htm",
        "http://www.pro-football-reference.com/players/R/RyanPa00.htm",
        "http://www.pro-football-reference.com/players/R/RypiMa00.htm",
        "http://www.pro-football-reference.com/players/S/SaccTo00.htm",
        "http://www.pro-football-reference.com/players/S/SacrNi20.htm",
        "http://www.pro-football-reference.com/players/S/SaliSe00.htm",
        "http://www.pro-football-reference.com/players/S/SantFr20.htm",
        "http://www.pro-football-reference.com/players/S/SarrCh20.htm",
        "http://www.pro-football-reference.com/players/S/SautCo00.htm",
        "http://www.pro-football-reference.com/players/S/ScarJa20.htm",
        "http://www.pro-football-reference.com/players/S/SchiHe20.htm",
        "http://www.pro-football-reference.com/players/S/SchlAr00.htm",
        "http://www.pro-football-reference.com/players/S/SchoTu00.htm",
        "http://www.pro-football-reference.com/players/S/SchrJa00.htm",
        "http://www.pro-football-reference.com/players/S/SchwBo00.htm",
        "http://www.pro-football-reference.com/players/S/SchwBu20.htm",
        "http://www.pro-football-reference.com/players/S/ScotBo00.htm",
        "http://www.pro-football-reference.com/players/S/ScraBo00.htm",
        "http://www.pro-football-reference.com/players/S/SebeNi20.htm",
        "http://www.pro-football-reference.com/players/S/SecuSc00.htm",
        "http://www.pro-football-reference.com/players/S/SeurFr00.htm",
        "http://www.pro-football-reference.com/players/S/ShawDe00.htm",
        "http://www.pro-football-reference.com/players/S/ShawGe00.htm",
        "http://www.pro-football-reference.com/players/S/SherAl20.htm",
        "http://www.pro-football-reference.com/players/S/SherSo20.htm",
        "http://www.pro-football-reference.com/players/S/SherTo00.htm",
        "http://www.pro-football-reference.com/players/S/ShieJo20.htm",
        "http://www.pro-football-reference.com/players/S/ShinDi00.htm",
        "http://www.pro-football-reference.com/players/S/ShulHe00.htm",
        "http://www.pro-football-reference.com/players/S/SimmCh00.htm",
        "http://www.pro-football-reference.com/players/S/SimmPh00.htm",
        "http://www.pro-football-reference.com/players/S/SipeBr00.htm",
        "http://www.pro-football-reference.com/players/S/SlauMi00.htm",
        "http://www.pro-football-reference.com/players/S/SloaSt00.htm",
        "http://www.pro-football-reference.com/players/S/SmitAk00.htm",
        "http://www.pro-football-reference.com/players/S/SmitRo03.htm",
        "http://www.pro-football-reference.com/players/S/SmitTr02.htm",
        "http://www.pro-football-reference.com/players/S/SneaNo00.htm",
        "http://www.pro-football-reference.com/players/S/SnydLo20.htm",
        "http://www.pro-football-reference.com/players/S/SongBu00.htm",
        "http://www.pro-football-reference.com/players/S/SorgJi00.htm",
        "http://www.pro-football-reference.com/players/S/SoutRo00.htm",
        "http://www.pro-football-reference.com/players/S/SproDe20.htm",
        "http://www.pro-football-reference.com/players/S/SpurSt00.htm",
        "http://www.pro-football-reference.com/players/S/St.PBr20.htm",
        "http://www.pro-football-reference.com/players/S/StabKe00.htm",
        "http://www.pro-football-reference.com/players/S/StanSc00.htm",
        "http://www.pro-football-reference.com/players/S/StanDr00.htm",
        "http://www.pro-football-reference.com/players/S/StanRi00.htm",
        "http://www.pro-football-reference.com/players/S/StarBa00.htm",
        "http://www.pro-football-reference.com/players/S/StauRo00.htm",
        "http://www.pro-football-reference.com/players/S/StenSt00.htm",
        "http://www.pro-football-reference.com/players/S/StepHa00.htm",
        "http://www.pro-football-reference.com/players/S/StepNi00.htm",
        "http://www.pro-football-reference.com/players/S/StepKa00.htm",
        "http://www.pro-football-reference.com/players/S/SterJo21.htm",
        "http://www.pro-football-reference.com/players/S/StevBi00.htm",
        "http://www.pro-football-reference.com/players/S/StevMa20.htm",
        "http://www.pro-football-reference.com/players/S/StevMa21.htm",
        "http://www.pro-football-reference.com/players/S/StewKo00.htm",
        "http://www.pro-football-reference.com/players/S/StoeCl00.htm",
        "http://www.pro-football-reference.com/players/S/StofJo00.htm",
        "http://www.pro-football-reference.com/players/S/StofKe20.htm",
        "http://www.pro-football-reference.com/players/S/StolAn20.htm",
        "http://www.pro-football-reference.com/players/S/StouCl00.htm",
        "http://www.pro-football-reference.com/players/S/StouKe00.htm",
        "http://www.pro-football-reference.com/players/S/StroDo00.htm",
        "http://www.pro-football-reference.com/players/S/StroRi00.htm",
        "http://www.pro-football-reference.com/players/S/SullPa00.htm",
        "http://www.pro-football-reference.com/players/S/SummCa00.htm",
        "http://www.pro-football-reference.com/players/S/SweeKe00.htm",
        "http://www.pro-football-reference.com/players/S/SweeKa00.htm",
        "http://www.pro-football-reference.com/players/T/TaggJe00.htm",
        "http://www.pro-football-reference.com/players/T/TaliMi00.htm",
        "http://www.pro-football-reference.com/players/T/TannAl00.htm",
        "http://www.pro-football-reference.com/players/T/TarkFr00.htm",
        "http://www.pro-football-reference.com/players/T/TarrJi21.htm",
        "http://www.pro-football-reference.com/players/T/TaylJi20.htm",
        "http://www.pro-football-reference.com/players/T/TaylTr00.htm",
        "http://www.pro-football-reference.com/players/T/TensSt00.htm",
        "http://www.pro-football-reference.com/players/T/TerlGe20.htm",
        "http://www.pro-football-reference.com/players/T/TestVi00.htm",
        "http://www.pro-football-reference.com/players/T/TheiJo00.htm",
        "http://www.pro-football-reference.com/players/T/TheoHa00.htm",
        "http://www.pro-football-reference.com/players/T/ThomBo02.htm",
        "http://www.pro-football-reference.com/players/T/ThomJa00.htm",
        "http://www.pro-football-reference.com/players/T/ThomKe00.htm",
        "http://www.pro-football-reference.com/players/T/ThomTo21.htm",
        "http://www.pro-football-reference.com/players/T/ThroWi20.htm",
        "http://www.pro-football-reference.com/players/T/TidwTr20.htm",
        "http://www.pro-football-reference.com/players/T/TinsSc20.htm",
        "http://www.pro-football-reference.com/players/T/TittY.00.htm",
        "http://www.pro-football-reference.com/players/T/ToddRi00.htm",
        "http://www.pro-football-reference.com/players/T/TollBi00.htm",
        "http://www.pro-football-reference.com/players/T/TolzSc00.htm",
        "http://www.pro-football-reference.com/players/T/TomcMi00.htm",
        "http://www.pro-football-reference.com/players/T/ToreGi00.htm",
        "http://www.pro-football-reference.com/players/T/TottWi20.htm",
        "http://www.pro-football-reference.com/players/T/TripFr00.htm",
        "http://www.pro-football-reference.com/players/T/TrocRi20.htm",
        "http://www.pro-football-reference.com/players/T/TrocBo20.htm",
        "http://www.pro-football-reference.com/players/T/TrouBi00.htm",
        "http://www.pro-football-reference.com/players/T/TrudJa00.htm",
        "http://www.pro-football-reference.com/players/T/TrulDo00.htm",
        "http://www.pro-football-reference.com/players/T/TuiaMa00.htm",
        "http://www.pro-football-reference.com/players/T/TupaTo20.htm",
        "http://www.pro-football-reference.com/players/T/TurnRi21.htm",
        "http://www.pro-football-reference.com/players/U/UnitJo00.htm",
        "http://www.pro-football-reference.com/players/V/VacaSa20.htm",
        "http://www.pro-football-reference.com/players/V/VanBNo00.htm",
        "http://www.pro-football-reference.com/players/V/VanGTi00.htm",
        "http://www.pro-football-reference.com/players/V/VanPAl00.htm",
        "http://www.pro-football-reference.com/players/V/VanPBr00.htm",
        "http://www.pro-football-reference.com/players/V/VanRJe20.htm",
        "http://www.pro-football-reference.com/players/V/VandRo00.htm",
        "http://www.pro-football-reference.com/players/V/VlasMa00.htm",
        "http://www.pro-football-reference.com/players/V/VoleBi00.htm",
        "http://www.pro-football-reference.com/players/W/WadeBi00.htm",
        "http://www.pro-football-reference.com/players/W/WadeTo00.htm",
        "http://www.pro-football-reference.com/players/W/WalkJa22.htm",
        "http://www.pro-football-reference.com/players/W/WallBe20.htm",
        "http://www.pro-football-reference.com/players/W/WallSe00.htm",
        "http://www.pro-football-reference.com/players/W/WalsSt00.htm",
        "http://www.pro-football-reference.com/players/W/WaltAn00.htm",
        "http://www.pro-football-reference.com/players/W/WaltDa20.htm",
        "http://www.pro-football-reference.com/players/W/WaltJo00.htm",
        "http://www.pro-football-reference.com/players/W/WardJi00.htm",
        "http://www.pro-football-reference.com/players/W/WareAn00.htm",
        "http://www.pro-football-reference.com/players/W/WarnKu00.htm",
        "http://www.pro-football-reference.com/players/W/WarrDe00.htm",
        "http://www.pro-football-reference.com/players/W/WateBo01.htm",
        "http://www.pro-football-reference.com/players/W/WateBo00.htm",
        "http://www.pro-football-reference.com/players/W/WatkFo20.htm",
        "http://www.pro-football-reference.com/players/W/WebeAd00.htm",
        "http://www.pro-football-reference.com/players/W/WeesNo00.htm",
        "http://www.pro-football-reference.com/players/W/WeinCh00.htm",
        "http://www.pro-football-reference.com/players/W/WeldCa00.htm",
        "http://www.pro-football-reference.com/players/W/WeldLa20.htm",
        "http://www.pro-football-reference.com/players/W/WellMi21.htm",
        "http://www.pro-football-reference.com/players/W/WheeMa00.htm",
        "http://www.pro-football-reference.com/players/W/WhelCr00.htm",
        "http://www.pro-football-reference.com/players/W/WhitDa01.htm",
        "http://www.pro-football-reference.com/players/W/WhitHa00.htm",
        "http://www.pro-football-reference.com/players/W/WhitCh02.htm",
        "http://www.pro-football-reference.com/players/W/WhitDa02.htm",
        "http://www.pro-football-reference.com/players/W/WhitTo20.htm",
        "http://www.pro-football-reference.com/players/W/WilhEr00.htm",
        "http://www.pro-football-reference.com/players/W/WillBo20.htm",
        "http://www.pro-football-reference.com/players/W/WillDo01.htm",
        "http://www.pro-football-reference.com/players/W/WillPe00.htm",
        "http://www.pro-football-reference.com/players/W/WillDr00.htm",
        "http://www.pro-football-reference.com/players/W/WilsDa00.htm",
        "http://www.pro-football-reference.com/players/W/WilsEd00.htm",
        "http://www.pro-football-reference.com/players/W/WilsGe00.htm",
        "http://www.pro-football-reference.com/players/W/WilsJo01.htm",
        "http://www.pro-football-reference.com/players/W/WilsMa00.htm",
        "http://www.pro-football-reference.com/players/W/WilsWa00.htm",
        "http://www.pro-football-reference.com/players/W/WitkJo00.htm",
        "http://www.pro-football-reference.com/players/W/WoodDi00.htm",
        "http://www.pro-football-reference.com/players/W/WoodGa00.htm",
        "http://www.pro-football-reference.com/players/W/WoodAl00.htm",
        "http://www.pro-football-reference.com/players/W/WoodTo02.htm",
        "http://www.pro-football-reference.com/players/W/WoodDa00.htm",
        "http://www.pro-football-reference.com/players/W/WoolSc20.htm",
        "http://www.pro-football-reference.com/players/W/WrigAn00.htm",
        "http://www.pro-football-reference.com/players/W/WrigRa00.htm",
        "http://www.pro-football-reference.com/players/W/WuerDa00.htm",
        "http://www.pro-football-reference.com/players/W/WyanFr20.htm",
        "http://www.pro-football-reference.com/players/W/WychSa00.htm",
        "http://www.pro-football-reference.com/players/W/WynnSp00.htm",
        "http://www.pro-football-reference.com/players/Y/YewcTo00.htm",
        "http://www.pro-football-reference.com/players/Y/YoueJi20.htm",
        "http://www.pro-football-reference.com/players/Y/YounSt00.htm",
        "http://www.pro-football-reference.com/players/Y/YounVi00.htm",
        "http://www.pro-football-reference.com/players/Z/ZeieEr00.htm",
        "http://www.pro-football-reference.com/players/Z/ZimmRo20.htm",
        "http://www.pro-football-reference.com/players/Z/ZolaSc00.htm",
        "http://www.pro-football-reference.com/players/Z/ZornJi00.htm",
        "http://www.pro-football-reference.com/players/A/AndeDe00.htm",
        "http://www.pro-football-reference.com/players/B/BatcCh00.htm",
        "http://www.pro-football-reference.com/players/B/BradSa00.htm",
        "http://www.pro-football-reference.com/players/B/BradTo00.htm",
        "http://www.pro-football-reference.com/players/B/BreeDr00.htm",
        "http://www.pro-football-reference.com/players/C/CampJa00.htm",
        "http://www.pro-football-reference.com/players/C/CarrDa00.htm",
        "http://www.pro-football-reference.com/players/C/CassMa00.htm",
        "http://www.pro-football-reference.com/players/C/ClemKe00.htm",
        "http://www.pro-football-reference.com/players/C/CousKi00.htm",
        "http://www.pro-football-reference.com/players/C/CutlJa00.htm",
        "http://www.pro-football-reference.com/players/D/DaltAn00.htm",
        "http://www.pro-football-reference.com/players/D/DaniCh00.htm",
        "http://www.pro-football-reference.com/players/D/DaviDo02.htm",
        "http://www.pro-football-reference.com/players/E/EdelJu00.htm",
        "http://www.pro-football-reference.com/players/E/EdwaAr00.htm",
        "http://www.pro-football-reference.com/players/E/EdwaTr01.htm",
        "http://www.pro-football-reference.com/players/F/FitzRy00.htm",
        "http://www.pro-football-reference.com/players/F/FlacJo00.htm",
        "http://www.pro-football-reference.com/players/F/FlynMa00.htm",
        "http://www.pro-football-reference.com/players/F/FoleNi00.htm",
        "http://www.pro-football-reference.com/players/F/FreeJo00.htm",
        "http://www.pro-football-reference.com/players/G/GabbBl00.htm",
        "http://www.pro-football-reference.com/players/G/GradBr00.htm",
        "http://www.pro-football-reference.com/players/G/GrifRo01.htm",
        "http://www.pro-football-reference.com/players/H/HarrGr00.htm",
        "http://www.pro-football-reference.com/players/H/HassMa00.htm",
        "http://www.pro-football-reference.com/players/H/HennCh01.htm",
        "http://www.pro-football-reference.com/players/H/HillSh00.htm",
        "http://www.pro-football-reference.com/players/H/HoyeBr00.htm",
        "http://www.pro-football-reference.com/players/J/JackTa00.htm",
        "http://www.pro-football-reference.com/players/J/JohnJo05.htm",
        "http://www.pro-football-reference.com/players/K/KaepCo00.htm",
        "http://www.pro-football-reference.com/players/K/KolbKe00.htm",
        "http://www.pro-football-reference.com/players/L/LeftBy00.htm",
        "http://www.pro-football-reference.com/players/L/LeinMa00.htm",
        "http://www.pro-football-reference.com/players/L/LewiTh01.htm",
        "http://www.pro-football-reference.com/players/L/LindRy00.htm",
        "http://www.pro-football-reference.com/players/L/LockJa00.htm",
        "http://www.pro-football-reference.com/players/L/LuckAn00.htm",
        "http://www.pro-football-reference.com/players/M/MallRy00.htm",
        "http://www.pro-football-reference.com/players/M/MannEl00.htm",
        "http://www.pro-football-reference.com/players/M/MannPe00.htm",
        "http://www.pro-football-reference.com/players/M/McCoLu00.htm",
        "http://www.pro-football-reference.com/players/M/McCoCo00.htm",
        "http://www.pro-football-reference.com/players/M/McElGr00.htm",
        "http://www.pro-football-reference.com/players/M/MoorMa01.htm",
        "http://www.pro-football-reference.com/players/N/NewtCa00.htm",
        "http://www.pro-football-reference.com/players/O/OrloDa00.htm",
        "http://www.pro-football-reference.com/players/O/OrtoKy00.htm",
        "http://www.pro-football-reference.com/players/O/OsweBr00.htm",
        "http://www.pro-football-reference.com/players/P/PalmCa00.htm",
        "http://www.pro-football-reference.com/players/P/PondCh00.htm",
        "http://www.pro-football-reference.com/players/P/PryoTe00.htm",
        "http://www.pro-football-reference.com/players/Q/QuinBr00.htm",
        "http://www.pro-football-reference.com/players/R/RivePh00.htm",
        "http://www.pro-football-reference.com/players/R/RodgAa00.htm",
        "http://www.pro-football-reference.com/players/R/RoetBe00.htm",
        "http://www.pro-football-reference.com/players/R/RomoTo00.htm",
        "http://www.pro-football-reference.com/players/R/RyanMa00.htm",
        "http://www.pro-football-reference.com/players/S/SancMa00.htm",
        "http://www.pro-football-reference.com/players/S/SchaMa00.htm",
        "http://www.pro-football-reference.com/players/S/SkelJo00.htm",
        "http://www.pro-football-reference.com/players/S/SmitAl03.htm",
        "http://www.pro-football-reference.com/players/S/SmitBr01.htm",
        "http://www.pro-football-reference.com/players/S/SmitRu01.htm",
        "http://www.pro-football-reference.com/players/S/StafMa00.htm",
        "http://www.pro-football-reference.com/players/T/TannRy00.htm",
        "http://www.pro-football-reference.com/players/T/TaylTy00.htm",
        "http://www.pro-football-reference.com/players/T/TeboTi00.htm",
        "http://www.pro-football-reference.com/players/T/ThigTy00.htm",
        "http://www.pro-football-reference.com/players/V/VickMi00.htm",
        "http://www.pro-football-reference.com/players/W/WeedBr00.htm",
        "http://www.pro-football-reference.com/players/W/WilsRu00.htm",
        "http://www.pro-football-reference.com/players/Y/YateT.00.htm"
    ]
    label_ref = {
        'Year' :      'year',
        'Age' :       'age',
        'Tm' :        'team',
        'Pos' :       'pos',
        'No.' :       'number',
        'G' :         'games_played',
        'GS' :        'games_started',
        'QBrec' :     'rec_in_gs',
        'Cmp' :       'completions',
        'Att' :       'att',
        'Cmp%' :      'completion_percentage',
        'Yds' :       'yds',
        'TD' :        'tds',
        'TD%' :       'td_percentage',
        'Int' :       'ints',
        'Int%' :      'int_percentage',
        'Lng' :       'longest_pass',
        'Y/A' :       'yds_per_att',
        'AY/A' :      'avg_yds_per_att',
        'Y/C' :       'yds_per_comp',
        'Y/G' :       'yds_per_game',
        'Rate' :      'rating',
        'QBR' :       'qbr',
        'Sk' :        'sacked',
        'Sk_Yds' :    'yds_lost_by_sack',
        'NY/A' :      'net_yds_per_att',
        'ANY/A' :     'adj_net_yds_per_att',
        'Sk%' :       'perc_times_sk',
        '4QC' :       'comebacks',
        'GWD' :       'gwds',
        'AV' :        'avg_value',
    }

    def parse(self, response):
        hxs = HtmlXPathSelector(response)
        item = QbItem()
        stat_ref = []

        # Get name
        name = hxs.select('//h1').select('text()').extract()
        name = re.search('\'(.*)\'', str(name)).group(1)
        item['name'] = name

        # Get height and weight
        pars = hxs.select('//p')
        for p in pars:
            content = str(p.select('text()').extract())
            if "lbs" in content:
                height = str(re.search('(\d+-\d+)', content).group(1)).split('-')
                converted_height = str(int(height[0]) * 12 + int(height[1]))
                item['height'] = converted_height
                item['weight'] = re.search('(\d+)\slbs', content).group(1)

        # Check which stats i'm getting
        stat_labels = hxs.select('//table[@id="passing"]/thead/tr/th')
        count = 0
        for label in stat_labels:
            label = str(label.select('text()').extract())
            label = re.search('\'(.*)\'', label).group(1)
            if count > 12 and label == "Yds":
                label = 'Sk_Yds'
            stat_ref.append(QbSpider.label_ref[label])
            count = count + 1

        # Get the stats
        stats_row = hxs.select('//table[@id="passing"]/tbody/tr')
        stat_arr = []
        row_count = 0
        for year_stats in stats_row:
            stats = year_stats.select('td')
            arr = []
            stat_count = 0
            for stat in stats:
                if len(stat.select('a').select('text()').extract()) == 0:
                    stat = str(stat.select('text()').extract())
                    stat = re.search('\'(.*)\'', stat)
                    if stat == None:
                        stat = "-999"
                    else:
                        stat = stat.group(1)
                else:
                    stat = str(stat.select('a').select('text()').extract())
                    stat = re.search('\'(.*)\'', stat)
                    if stat == None:
                        stat = "-999"
                    else:
                        stat = stat.group(1)
                if stat_count == 6 and int(stat) < 7:
                    arr = []
                    break
                if stat_count == 7 and stat != "-999":
                    stat = stat.replace('-', '_')
                arr.append(stat)
                stat_count = stat_count + 1

            if len(arr) > 0:
                stat_arr = arr
                break

        count = 0
        for stat in stat_arr:
            item[stat_ref[count]] = stat
            count = count + 1

        if len(stat_arr) == 0:
            item = []

        return item
